import { Header } from "@/components/layout/header";
import { Footer } from "@/components/layout/footer";
import { Card, CardContent } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { FileScan, Database, Workflow, Archive, ShieldCheck, BarChart3, ArrowRight } from "lucide-react";
import { Link } from "wouter";

const services = [
  ["Document Digitization", "Convert paper archives into structured, searchable digital records. Suitable for backlogs, active registries and project-based scanning.", FileScan],
  ["Data Capture & Indexing", "Design consistent metadata structures and capture information that makes records easy to retrieve and use.", BarChart3],
  ["EDMS & Records Management", "Plan, configure and implement electronic document and records management environments around real business workflows.", Database],
  ["Workflow Automation", "Connect documents, approvals, tasks and users to reduce manual handoffs and improve process visibility.", Workflow],
  ["Records & Archive Management", "Bring order to physical and digital records through classification, inventory, retention and retrieval practices.", Archive],
  ["Secure Document Disposal", "Support controlled destruction and disposal of records that have reached the end of their approved lifecycle.", ShieldCheck],
];

export default function Services() {
  return <div className="min-h-screen"><Header /><main className="pt-16">
    <section className="py-20 bg-gradient-to-br from-primary via-primary/90 to-accent text-white"><div className="max-w-6xl mx-auto px-4 sm:px-6 lg:px-8 text-center"><p className="text-sm font-semibold uppercase tracking-widest text-blue-100 mb-4">Henox Solutions</p><h1 className="text-4xl md:text-6xl font-bold mb-6">Information Solutions Built Around Your Business</h1><p className="text-xl md:text-2xl text-blue-100 max-w-4xl mx-auto leading-relaxed">From document backlogs to digital workflows, we help organizations create practical, controlled paths to better information management.</p></div></section>
    <section className="py-20 bg-white"><div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8"><div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-8">{services.map(([title, description, Icon]) => { const ServiceIcon = Icon as typeof FileScan; return <Card key={title as string} className="service-card-hover border-gray-100"><CardContent className="p-7"><div className="w-12 h-12 bg-primary/10 rounded-xl flex items-center justify-center mb-5"><ServiceIcon className="text-primary" size={23} /></div><h2 className="text-xl font-bold text-gray-900 mb-3">{title as string}</h2><p className="text-gray-600 leading-relaxed mb-6">{description as string}</p><Button asChild variant="outline" className="border-primary text-primary hover:bg-primary hover:text-white"><Link href="/contact">Discuss This Solution <ArrowRight className="ml-2" size={16} /></Link></Button></CardContent></Card>})}</div></div></section>
    <section className="py-20 bg-gradient-to-br from-gray-50 to-blue-50/30"><div className="max-w-6xl mx-auto px-4 sm:px-6 lg:px-8"><div className="text-center mb-12"><div className="inline-block px-4 py-2 bg-primary/10 text-primary rounded-full text-sm font-medium mb-4">Delivery Method</div><h2 className="text-4xl font-bold text-gray-900 mb-4">A Controlled Project Lifecycle</h2><p className="text-xl text-gray-600 max-w-3xl mx-auto">Every engagement is scoped around your records, security requirements, volumes, workflows and desired outcomes.</p></div><div className="grid grid-cols-1 md:grid-cols-4 gap-6">{[["01","Discover","Understand the records, process, risks and objectives."],["02","Design","Define the capture, indexing, technology and delivery model."],["03","Deliver","Execute with quality controls, reporting and agreed governance."],["04","Improve","Review outcomes and identify opportunities for automation and optimization."]].map(([n,t,d])=><Card key={n} className="bg-white border-gray-100"><CardContent className="p-6"><span className="text-accent font-bold">{n}</span><h3 className="text-xl font-semibold text-gray-900 mt-3 mb-2">{t}</h3><p className="text-gray-600 text-sm leading-relaxed">{d}</p></CardContent></Card>)}</div></div></section>
    <section className="py-20 bg-gradient-to-br from-primary to-accent text-white text-center"><div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8"><h2 className="text-4xl font-bold mb-5">Let's scope the right solution.</h2><p className="text-xl text-blue-100 mb-8">No generic package. We assess the problem and design the engagement around your organization.</p><Button asChild size="lg" className="bg-white text-primary hover:bg-gray-100"><Link href="/contact">Request a Consultation <ArrowRight className="ml-2" size={18} /></Link></Button></div></section>
  </main><Footer /></div>;
}
